organization:
  name: Broadview Networks
  url: www.BroadviewNet.com

spring:
  datasource:
    url: jdbc:jtds:sqlserver://${DATABASE-SERVER:Localhost}/${DATABASE:MYDB};TDS=8.0;appName=${APP-NAME:NA};namedPipe=false;autoReconnect=true;autoReconnectForPools=true
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    username: ${DB-USERNAME:sa}
    password: ${DB-PASSWORD:password}
    maximum-pool-size: 30
    testOnBorrow: true
    test-on-borrow: true
    validationQuery: SELECT 1
  
  jpa: 
    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      
  cloud:
    config:
      uri: http://localhost:8888
