organization:
  name: Broadview Networks
  url: www.BroadviewNet.com

spring:
  datasource:
    url: jdbc:jtds:sqlserver://${DATABASE-SERVER:Localhost}/${DATABASE:SCS};TDS=8.0;appName=${APP-NAME:NA};namedPipe=false;autoReconnect=true;autoReconnectForPools=true
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    username: ${DB-USERNAME:sa}
    password: ${DB-PASSWORD:password}
    maximum-pool-size: 30
  cloud:
    config:
      uri: http://localhost:8888
